export declare const IS_PROD: boolean;
export declare const SRC_DIR: string;
export declare var EXPORT_DIR: string;
export declare const ANDROID_MANIFEST = "AndroidManifest.xml";
export declare const APP_DATA_XSJ = "appdataxsj";
export declare const APP_CHECK_JAR = "lib/AppCheck.jar";
export declare const APP_DATA_FOLDER: string;
export declare const GMS_OUTPUT: string;
export declare const HMS_OUTPUT: string;
export declare const APKTOOL_JAR = "lib/apktool.jar";
export declare const DECOMPILE_FOLDER: string;
export declare const CHROMIUM_REVISION = 970485;
export declare const CHROMIUM_EXEC_PATH: string;
export declare const CHROMIUM_INSTALL_PATH: string;
export declare const DOWNLOAD_FOLDER: string;
export declare const TEMP_FOLDER: string;
export declare const LOG_FOLDER: string;
export declare const OUT_LOG_FILE: string;
export declare const ERR_LOG_FILE: string;
export declare const MAX_PACKAGE_NAMES = 200;
export declare const DEFAULT_BATCH_SIZE = 3;
export declare const UNKNOWN_INFO = "";
export declare const GOOGLE_MESSAGING_EVENT = "com.google.firebase.MESSAGING_EVENT";
export declare const HUAWEI_MESSAGING_EVENT = "com.huawei.push.action.MESSAGING_EVENT";
